export const dom_canvas   = document.querySelector('.canvas')
export const dom_payout   = document.querySelector('.payout')
export const dom_totalWin = document.querySelector('.totalWin')
export const dom_balance  = document.querySelector('.balance')
export const dom_stake    = document.querySelector('.stake')